purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1875
  brandStrength: 0.875
  rhythmicContrast: 0.75
  brandColors:
    - '#526988'
    - '#a7b4c4'
    - '#243958'
    - '#ffffff'
    - '#0f1111'
  lightness: 0.6351353861391544
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: DJ Sepp
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2939068
layout_spectrum: 0.2526882
