name: DJ Sepp
favicon: null
layout_spectrum: 0.24845
typography_spectrum: 0.65299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#526988'
    - '#a7b4c4'
    - '#243958'
    - '#ffffff'
    - '#0f1111'
  brandStrength: 0.875
  lightness: 0.6351353861391544
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
